#!/bin/bash

## Introductory Example for running Mr. Bayes
## Copyright (c) 2013 The Center for Advanced Research Computing
##                            at The University of New Mexico


#PBS -lnodes=1:ppn=8
#PBS -lwalltime=24:00:00
#PBS -S /bin/bash

# Load the environment modules system
source /etc/profile.d/modules.sh

# Load the environment module for mrbayes version 3.2.4
# This also loads the associated openmpi library and beagle
module load openmpi/1.10.0/gcc/4.8.4

#Make sure everything is Linux compatable
dos2unix ./*

# Change to the directory that this job was submitted from
cd $PBS_O_WORKDIR

# Set up license file:
export ABAQUSLM_LICENSE_FILE=27004@129.24.132.53

/users/acowan/abq/Commands/abaqus cpus=4 mp_mode=mpi job=Beam-3 input=Beam-3.inp


